version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_PASS
      MYSQL_DATABASE: internship
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: