apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-persistent-volume
spec:
  storageClassName: standard
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: /data/myapp