apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-persistent-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}